language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
    - test/node_modules
install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - grunt lint
script:
  - grunt test
  - if [ -d test/node_modules ]; then mv test/node_modules test/tmp/polymer-app/node_modules; fi
  - cd test/tmp/polymer-app/ && npm install && grunt test
after_script:
  - mv node_modules ../../node_modules
