language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - grunt lint
script:
  - grunt test
  - cd test/tmp/polymer-app/ && npm install
  - pwd
